### ISSUE TITLE
Titan 0.9 and Tinkerpop 3

### ISSUE THREAD

**Issue by oren** [jbmusso/grex#60]
I would like to use Titan 0.9. Are you planning to support it? if not, should I just use the `request` module directly?

**Comment by jbmusso** [comment]
Your best bet is to use https://github.com/jbmusso/gremlin-client which supports TinkerPop3 :).

**Comment by jbmusso** [comment]
More precisely, I don't think I'll add support for TP3 over HTTP in gRex (see http://tinkerpop.incubator.apache.org/docs/3.0.0-incubating/#_connecting_via_rest). I think this should be added in gremlin-client, which is meant to be an all-around TP3 client.

**Comment by oren** [comment]
fantastic! I wasn't aware of gremlin-client. it uses WebSocket so I assume the it will also be faster. I'll give it a try.
