### ISSUE TITLE
Replication

### ISSUE THREAD

**Issue by nawazdhandala** [jbmusso/grex#61]
How can I have more than one URL's in hostname (replica-set) in createClient()?

**Comment by jbmusso** [comment]
Unfortunately, you can't do that at the moment with gRex - you have to manage this by yourself : typically, you'll want to instantiate as many clients as you have servers, create a client that a) wraps them all and b) does the load balancing. I agree with you that this should be supported at the client level and I plan to add support for this in https://github.com/jbmusso/gremlin-javascript (TinkerPop 3 Websocket client).
